# Generated by Django 3.0.4 on 2020-03-21 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150, verbose_name='Текст вопроса')),
                ('answer', models.BooleanField(default=False, verbose_name='Ответы')),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('old', models.IntegerField(verbose_name='Возраст')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
        ),
        migrations.CreateModel(
            name='Sith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siths', to='workTest.Planet', verbose_name='Планета')),
            ],
        ),
        migrations.CreateModel(
            name='ResultTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(default=False, verbose_name='Результат')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workTest.Recruit', verbose_name='Рекрут')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workTest.Question', verbose_name='Испытание')),
            ],
        ),
        migrations.AddField(
            model_name='recruit',
            name='hand_shadow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciples', to='workTest.Sith', verbose_name='Рука тени'),
        ),
        migrations.AddField(
            model_name='recruit',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruits', to='workTest.Planet', verbose_name='Планета'),
        ),
    ]
