# Generated by Django 3.0.4 on 2020-05-17 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workTest', '0003_recruit_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='hand_shadow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciples', to='workTest.Sith', verbose_name='Рука тени'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruits', to='workTest.ResultTest'),
        ),
    ]
