# Generated by Django 3.0.4 on 2020-05-18 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workTest', '0004_auto_20200517_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resulttest',
            old_name='result',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='resulttest',
            old_name='test',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
    ]
