# Generated by Django 3.0.4 on 2020-05-19 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workTest', '0006_auto_20200519_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='hand_shadow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciples', to='workTest.Sith', verbose_name='Рука тени'),
        ),
    ]
